---
- name: Restart pm2
  become_user: "{{ app_user }}"
  shell: |
    export HOME=/home/{{ app_user }}
    cd {{ deploy_dir }}/api
    pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
